export const CHECKOUT_ENTER = 'CHECKOUT_ENTER';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL';
export const CHECKOUT_DATA = 'CHECKOUT_DATA';
export const CHECKOUT_STATE = 'CHECKOUT_STATE';
export const CHECKOUT_PROCESS = 'CHECKOUT_PROCESS';
export const CHECKOUT_FETCH_TOTALS = 'CHECKOUT_FETCH_TOTALS';
export const CHECKOUT_TOTALS = 'CHECKOUT_TOTALS';
