const CHECKOUT = 'checkout';
const CART = 'cart';
const SHIPPING_ADDRESS = 'shipping_address';
const BILLING_ADDRESS = 'billing_address';
const PAYMENT_METHOD = 'payment_method';
const SHIPPING_METHOD = 'shipping_method';
const CUSTOM_FIELDS = 'custom_fields';
const PROCESS = 'process';
const BEFORE = 'before';
const AFTER = 'after';

export const CHECKOUT_CART_BEFORE = `${CHECKOUT}.${CART}.${BEFORE}`;
export const CHECKOUT_CART = `${CHECKOUT}.${CART}`;
export const CHECKOUT_CART_AFTER = `${CHECKOUT}.${CART}.${AFTER}`;

export const CHECKOUT_SHIPPING_ADDRESS_BEFORE = `${CHECKOUT}.${SHIPPING_ADDRESS}.${BEFORE}`;
export const CHECKOUT_SHIPPING_ADDRESS = `${CHECKOUT}.${SHIPPING_ADDRESS}`;
export const CHECKOUT_SHIPPING_ADDRESS_AFTER = `${CHECKOUT}.${SHIPPING_ADDRESS}.${AFTER}`;

export const CHECKOUT_BILLING_ADDRESS_BEFORE = `${CHECKOUT}.${BILLING_ADDRESS}.${BEFORE}`;
export const CHECKOUT_BILLING_ADDRESS = `${CHECKOUT}.${BILLING_ADDRESS}`;
export const CHECKOUT_BILLING_ADDRESS_AFTER = `${CHECKOUT}.${BILLING_ADDRESS}.${AFTER}`;

export const CHECKOUT_PAYMENT_METHOD_BEFORE = `${CHECKOUT}.${PAYMENT_METHOD}.${BEFORE}`;
export const CHECKOUT_PAYMENT_METHOD = `${CHECKOUT}.${PAYMENT_METHOD}`;
export const CHECKOUT_PAYMENT_METHOD_AFTER = `${CHECKOUT}.${PAYMENT_METHOD}.${AFTER}`;

export const CHECKOUT_SHIPPING_METHOD_BEFORE = `${CHECKOUT}.${SHIPPING_METHOD}.${BEFORE}`;
export const CHECKOUT_SHIPPING_METHOD = `${CHECKOUT}.${SHIPPING_METHOD}`;
export const CHECKOUT_SHIPPING_METHOD_AFTER = `${CHECKOUT}.${SHIPPING_METHOD}.${AFTER}`;

export const CHECKOUT_CUSTOM_FIELDS_BEFORE = `${CHECKOUT}.${CUSTOM_FIELDS}.${BEFORE}`;
export const CHECKOUT_CUSTOM_FIELDS = `${CHECKOUT}.${CUSTOM_FIELDS}`;
export const CHECKOUT_CUSTOM_FIELDS_AFTER = `${CHECKOUT}.${CUSTOM_FIELDS}.${AFTER}`;

export const CHECKOUT_PROCESS_BEFORE = `${CHECKOUT}.${PROCESS}.${BEFORE}`;
export const CHECKOUT_PROCESS = `${CHECKOUT}.${PROCESS}`;
export const CHECKOUT_PROCESS_AFTER = `${CHECKOUT}.${PROCESS}.${AFTER}`;
